import type { Metadata } from "next";

import "@/styles/globals.css";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Khati",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased flex flex-col min-h-screen bg-white text-foreground`}
      >
        <Header />

        <main className="h-full grow">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
