import type { Metadata } from "next";
import { Lato } from "next/font/google";

import "@/styles/globals.css";
import { cn } from "@/lib/utils";

import Header from "@/components/layout/Header";

const font = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Khati",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(font.className)}>
        <Header />
        <main className="bg-gray-100 h-full w-full">{children}</main>
      </body>
    </html>
  );
}
